_format_version: '1.1'
_info:
  defaults: {}
  select_tags:
    - app_mentalHealthCounselorApplication3928940134
    - consumer
_workspace: TelusDigitalTest
consumers:
  - username: mentalHealthCounselorApplication3928940134
    custom_id: 417be8ca-c738-4574-86cc-6cb47055a7a6
    acls: []
